# Generated by Django 4.2.20 on 2025-10-24 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('SI_NO', 'Sí o No + Comentarios'), ('VALORACION', 'Bueno / Regular / Malo + Comentarios'), ('COMENTARIO', 'Solo Comentarios')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('ponderacion', models.FloatField(default=1.0)),
                ('pregunta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas_hijas', to='supervision.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficina', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='supervision.formulario')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('ponderacion', models.FloatField(default=1.0)),
                ('activo', models.BooleanField(default=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='supervision.formulario')),
            ],
        ),
        migrations.CreateModel(
            name='SubSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('ponderacion', models.FloatField(default=1.0)),
                ('activo', models.BooleanField(default=True)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsecciones', to='supervision.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=20, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('habilitada', models.BooleanField(default=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.pregunta')),
                ('respuesta_formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='supervision.respuestaformulario')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='subseccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='supervision.subseccion'),
        ),
    ]
