# Generated by Django 4.2.20 on 2025-12-19 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0037_acciones_antecedente_alter_area_name'),
        ('supervision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTemporal',
            fields=[
                ('idRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('claveAcuerdo', models.CharField(default='Clave de Acuerdo', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('estado', models.CharField(choices=[('1', 'En proceso'), ('2', 'Atendido')], default='1', max_length=1)),
                ('fecha_finalizacion', models.DateField(default='1970-01-01')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('porcentaje_avance', models.IntegerField(default=0)),
                ('area', models.ManyToManyField(related_name='registroATemporal', to='usuarios.area')),
                ('periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.periodo')),
                ('rubro', models.ManyToManyField(related_name='registroRTemporal', to='usuarios.rubro')),
            ],
        ),
        migrations.CreateModel(
            name='AccionesTemporal',
            fields=[
                ('idAccion', models.AutoField(primary_key=True, serialize=False)),
                ('antecedente', models.TextField(blank=True)),
                ('descripcion', models.TextField()),
                ('area2', models.ManyToManyField(related_name='accionA2Temporal', to='usuarios.area')),
                ('idRegistro', models.ManyToManyField(related_name='accionRTemporal', to='supervision.registrotemporal')),
            ],
        ),
    ]
