# Generated by Django 5.0.4 on 2024-04-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('idArea', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('idRubro', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Acciones',
            fields=[
                ('idAccion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('area1', models.ManyToManyField(related_name='accionA1', to='usuarios.area')),
                ('area2', models.ManyToManyField(related_name='accionA2', to='usuarios.area')),
            ],
        ),
        migrations.CreateModel(
            name='Pruebas',
            fields=[
                ('idPruebas', models.AutoField(primary_key=True, serialize=False)),
                ('nom_archivo', models.TextField()),
                ('tipo', models.CharField(choices=[('1', 'URL'), ('2', 'Local')], default='1', max_length=1)),
                ('archivo_url', models.TextField()),
                ('acciones', models.ManyToManyField(related_name='accionP', to='usuarios.acciones')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('idRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('estado', models.CharField(choices=[('1', 'En proceso'), ('2', 'Atendido')], default='1', max_length=1)),
                ('area', models.ManyToManyField(related_name='registroA', to='usuarios.area')),
                ('rubro', models.ManyToManyField(related_name='registroR', to='usuarios.rubro')),
            ],
        ),
        migrations.AddField(
            model_name='acciones',
            name='idRegistro',
            field=models.ManyToManyField(related_name='accionR', to='usuarios.registro'),
        ),
    ]
