# Generated by Django 4.2.20 on 2026-03-08 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('idArea', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=150)),
                ('name', models.CharField(default='Area 1', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('corto', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sede', models.CharField(max_length=100)),
                ('abrev', models.CharField(max_length=20)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficinas', to='usuarios.estados')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('idRubro', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioP',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('1', 'Administrador'), ('2', 'Editor')], default='3', max_length=1)),
                ('oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuarios.oficina')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuarioP', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('idRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('claveAcuerdo', models.CharField(default='Clave de Acuerdo', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('estado', models.CharField(choices=[('1', 'En proceso'), ('2', 'Atendido')], default='1', max_length=1)),
                ('fecha_finalizacion', models.DateField(default='1970-01-01')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('porcentaje_avance', models.IntegerField(default=0)),
                ('area', models.ManyToManyField(related_name='registroA', to='usuarios.oficina')),
                ('periodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.periodo')),
                ('rubro', models.ManyToManyField(related_name='registroR', to='usuarios.rubro')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_leido', models.DateTimeField(auto_now_add=True, null=True)),
                ('registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.registro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='mensajes/')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='usuarios.registro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Acciones',
            fields=[
                ('idAccion', models.AutoField(primary_key=True, serialize=False)),
                ('antecedente', models.TextField(blank=True)),
                ('descripcion', models.TextField()),
                ('area2', models.ManyToManyField(related_name='accionA2', to='usuarios.oficina')),
                ('idRegistro', models.ManyToManyField(related_name='accionR', to='usuarios.registro')),
            ],
        ),
    ]
