# Generated by Django 5.0.4 on 2024-04-13 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=250)),
                ('estado', models.CharField(choices=[('1', 'AGUASCALIENTES'), ('2', 'BAJA CALIFORNIA'), ('3', 'BAJA CALIFORNIA SUR'), ('4', 'CAMPECHE'), ('5', 'COAHUILA'), ('6', 'COLIMA'), ('7', 'CHIAPAS'), ('8', 'CHIHUAHUA'), ('9', 'CDMX'), ('10', 'DURANGO'), ('11', 'GUANAJUATO'), ('12', 'GUERRERO'), ('13', 'HIDALGO'), ('14', 'JALISCO'), ('15', 'EDOMEX'), ('16', 'MICHOACÁN'), ('17', 'MORELOS'), ('18', 'NAYARIT'), ('19', 'NUEVO LEÓN'), ('20', 'OAXACA'), ('21', 'PUEBLA'), ('22', 'QUERÉTARO'), ('23', 'QUINTANA ROO'), ('24', 'SAN LUIS POTOSÍ'), ('25', 'SINALOA'), ('26', 'SONORA'), ('27', 'TABASCO'), ('28', 'TAMAULIPAS'), ('29', 'TLAXCALA'), ('30', 'VERACRUZ'), ('31', 'YUCATÁN'), ('32', 'ZACATECAS')], default='9', max_length=2)),
                ('tipo', models.CharField(choices=[('1', 'Administrador'), ('2', 'Validador'), ('3', 'Capturador')], default='3', max_length=1)),
            ],
        ),
    ]
