# Generated by Django 5.0.4 on 2024-04-16 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_registro_rubro_registro_rubro'),
    ]

    operations = [
        migrations.CreateModel(
            name='registroA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.area')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.registro')),
            ],
        ),
    ]
