# Generated by Django 5.0.4 on 2024-04-16 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_registroa'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarioA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuariol')),
            ],
        ),
    ]
