# Generated by Django 5.0.4 on 2024-04-16 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuarioa'),
    ]

    operations = [
        migrations.CreateModel(
            name='accionA1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.area')),
                ('idAccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.acciones')),
            ],
        ),
        migrations.CreateModel(
            name='accionA2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.area')),
                ('idAccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.acciones')),
            ],
        ),
        migrations.CreateModel(
            name='accionR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.acciones')),
                ('idRegistro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.registro')),
            ],
        ),
    ]
