# Generated by Django 5.0.4 on 2024-04-16 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_acciona1_acciona2_accionr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acciones',
            name='area1',
        ),
        migrations.RemoveField(
            model_name='acciones',
            name='area2',
        ),
        migrations.RemoveField(
            model_name='acciones',
            name='idRegistro',
        ),
        migrations.RemoveField(
            model_name='pruebas',
            name='acciones',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='area',
        ),
        migrations.RemoveField(
            model_name='usuariol',
            name='area',
        ),
        migrations.CreateModel(
            name='accionP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.area')),
                ('idPruebas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.pruebas')),
            ],
        ),
    ]
