# Generated by Django 5.0.4 on 2024-04-16 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_acciones_area1_remove_acciones_area2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accionp',
            name='acciones',
        ),
        migrations.AddField(
            model_name='accionp',
            name='idAccion',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='usuarios.acciones'),
        ),
    ]
