# Generated by Django 5.0.4 on 2024-04-16 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_remove_accionp_acciones_accionp_idaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accionp',
            name='idAccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.acciones'),
        ),
    ]
