# Generated by Django 5.0.4 on 2024-04-17 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_alter_accionr_idregistro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acciona2',
            name='area2',
        ),
        migrations.RemoveField(
            model_name='acciona2',
            name='idAccion',
        ),
        migrations.RemoveField(
            model_name='accionp',
            name='idAccion',
        ),
        migrations.RemoveField(
            model_name='accionp',
            name='idPruebas',
        ),
        migrations.RemoveField(
            model_name='accionr',
            name='idAccion',
        ),
        migrations.RemoveField(
            model_name='accionr',
            name='idRegistro',
        ),
        migrations.RemoveField(
            model_name='registroa',
            name='Area',
        ),
        migrations.RemoveField(
            model_name='registroa',
            name='registro',
        ),
        migrations.RemoveField(
            model_name='usuarioa',
            name='Area',
        ),
        migrations.RemoveField(
            model_name='usuarioa',
            name='user',
        ),
        migrations.AddField(
            model_name='acciones',
            name='area1',
            field=models.ManyToManyField(related_name='accionA1', to='usuarios.area'),
        ),
        migrations.AddField(
            model_name='acciones',
            name='area2',
            field=models.ManyToManyField(related_name='accionA2', to='usuarios.area'),
        ),
        migrations.AddField(
            model_name='acciones',
            name='idRegistro',
            field=models.ManyToManyField(related_name='accionR', to='usuarios.registro'),
        ),
        migrations.AddField(
            model_name='pruebas',
            name='acciones',
            field=models.ManyToManyField(related_name='accionP', to='usuarios.acciones'),
        ),
        migrations.AddField(
            model_name='registro',
            name='area',
            field=models.ManyToManyField(related_name='registroA', to='usuarios.area'),
        ),
        migrations.RemoveField(
            model_name='registro',
            name='rubro',
        ),
        migrations.DeleteModel(
            name='accionA1',
        ),
        migrations.DeleteModel(
            name='accionA2',
        ),
        migrations.DeleteModel(
            name='accionP',
        ),
        migrations.DeleteModel(
            name='accionR',
        ),
        migrations.DeleteModel(
            name='registroA',
        ),
        migrations.DeleteModel(
            name='usuarioA',
        ),
        migrations.AddField(
            model_name='registro',
            name='rubro',
            field=models.ManyToManyField(related_name='registroR', to='usuarios.rubro'),
        ),
    ]
