# Generated by Django 5.0.4 on 2024-07-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_area_abrevarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='nickname',
            field=models.CharField(max_length=150),
        ),
    ]
