# Generated by Django 5.0.4 on 2024-07-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_area_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('1', 'Administrador'), ('2', 'Editor')], default='3', max_length=1),
        ),
    ]
