# Generated by Django 4.2.6 on 2024-07-11 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_alter_usuariop_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuariop',
            old_name='estado',
            new_name='OR',
        ),
    ]
