# Generated by Django 4.2.6 on 2024-07-11 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_rename_estado_usuariop_or'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acciones',
            name='area1',
        ),
    ]
