# Generated by Django 4.2.6 on 2024-07-11 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_remove_acciones_area1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pruebas',
        ),
    ]
