# Generated by Django 4.2.6 on 2024-07-11 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_delete_pruebas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='abrevArea',
        ),
    ]
