# Generated by Django 4.2.6 on 2024-07-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0027_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='name',
            field=models.CharField(default='Nombre de Area', max_length=300),
        ),
    ]
