# Generated by Django 4.2.6 on 2024-07-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0029_registro_fecha_finalizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha_finalizacion',
            field=models.DateField(default=''),
        ),
    ]
