# Generated by Django 4.2.6 on 2024-09-19 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0033_alter_registro_fecha_finalizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='porcentaje_avance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registro',
            name='claveAcuerdo',
            field=models.CharField(default='Clave de Acuerdo', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuariop',
            name='OR',
            field=models.CharField(choices=[('1', 'OR AGS'), ('2', 'OR BC'), ('3', 'OR BCS'), ('4', 'OR CAMP'), ('5', 'OR COAH'), ('6', 'OR COL'), ('7', 'OR CHIS'), ('8', 'OR CHIH'), ('9', 'OR CDMX'), ('10', 'OR DGO'), ('11', 'OR GTO'), ('12', 'OR GRO'), ('13', 'OR HGO'), ('14', 'OR JAL'), ('15', 'OR EDOMEX'), ('16', 'OR MICH'), ('17', 'OR MOR'), ('18', 'OR NAY'), ('19', 'OR NL'), ('20', 'OR OAX'), ('21', 'OR PUE'), ('22', 'OR QRO'), ('23', 'OR QROO'), ('24', 'OR SLP'), ('25', 'OR SIN'), ('26', 'OR SON'), ('27', 'OR TAB'), ('28', 'OR TAMPS'), ('29', 'OR TLX'), ('30', 'OR VER'), ('31', 'OR YUC'), ('32', 'OR ZAC'), ('33', 'OC'), ('34', 'OSCJ'), ('35', 'CECC'), ('36', 'DCS'), ('37', 'DGA'), ('38', 'DGCOR'), ('39', 'DGCVM'), ('40', 'DGPMV'), ('41', 'DGRAM'), ('42', 'DGTIC'), ('43', 'AICMX'), ('44', 'DC')], default='9', max_length=2),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_leido', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
