# Generated by Django 4.2.20 on 2025-08-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0036_periodo_registro_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciones',
            name='antecedente',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(default='Area 1', max_length=300),
        ),
    ]
